// <auto-generated />
using System;
using AITasker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AITasker.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AITaskerDbContext))]
    [Migration("20260609114812_AddReviewReviewerCheckConstraint")]
    partial class AddReviewReviewerCheckConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AITasker.Domain.Entities.BusinessProfile", b =>
                {
                    b.Property<int>("BusinessProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessProfileId"));

                    b.Property<string>("BusinessEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BusinessPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BusinessProfileId");

                    b.HasIndex("ClientProfileId")
                        .IsUnique();

                    b.HasIndex("TaxCode")
                        .IsUnique();

                    b.ToTable("BusinessProfiles", (string)null);
                });

            modelBuilder.Entity("AITasker.Domain.Entities.ClientProfile", b =>
                {
                    b.Property<int>("ClientProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientProfileId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AiNeeds")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ExpectedBudgetMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ExpectedBudgetMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MainProblems")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("PlatformFeeRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ClientProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ClientProfiles", (string)null);
                });

            modelBuilder.Entity("AITasker.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<int>("EmailVerificationTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailVerificationTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmailVerificationTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerificationTokens", (string)null);
                });

            modelBuilder.Entity("AITasker.Domain.Entities.ExpertCertificate", b =>
                {
                    b.Property<int>("ExpertCertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpertCertificateId"));

                    b.Property<string>("CertificateIssuer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CertificateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CertificateUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpertProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ExpertCertificateId");

                    b.HasIndex("ExpertProfileId", "CertificateUrl")
                        .IsUnique();

                    b.ToTable("ExpertCertificates", (string)null);
                });

            modelBuilder.Entity("AITasker.Domain.Entities.ExpertProfile", b =>
                {
                    b.Property<int>("ExpertProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpertProfileId"));

                    b.Property<bool>("AvailableForWork")
                        .HasColumnType("bit");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("CompletedProjects")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExpectedProjectBudgetMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExpectedProjectBudgetMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExpertCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GitHubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MissingInformation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PreferredProjectDurationDays")
                        .HasColumnType("int");

                    b.Property<string>("ProfessionalTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProfileReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ProfileReviewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("ProfileScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RatingAverage")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("ExpertProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ExpertProfiles", (string)null);
                });

            modelBuilder.Entity("AITasker.Domain.Entities.ExpertSkill", b =>
                {
                    b.Property<int>("ExpertSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpertSkillId"));

                    b.Property<int>("ExpertProfileId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("ExpertSkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("ExpertProfileId", "SkillId")
                        .IsUnique();

                    b.ToTable("ExpertSkills", (string)null);
                });

            modelBuilder.Entity("AITasker.Domain.Entities.JobPosting", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<string>("AIgeneratedDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BudgetMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BudgetMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Complexity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedDeliverables")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAIAssisted")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("JobId");

                    b.HasIndex("ClientProfileId", "Status");

                    b.HasIndex("Status", "Deadline");

                    b.ToTable("JobPostings", (string)null);
                });

            modelBuilder.Entity("AITasker.Domain.Entities.JobSkill", b =>
                {
                    b.Property<int>("JobSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobSkillId"));

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("SkillLevelRequired")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("JobSkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("JobId", "SkillId")
                        .IsUnique();

                    b.ToTable("JobSkills", (string)null);
                });

            modelBuilder.Entity("AITasker.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("PasswordResetTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PasswordResetTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PasswordResetTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("AITasker.Domain.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpertProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("ProposalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProjectId");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("ExpertProfileId");

                    b.HasIndex("ProposalId");

                    b.HasIndex("Status");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("AITasker.Domain.Entities.Proposal", b =>
                {
                    b.Property<int>("ProposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProposalId"));

                    b.Property<string>("CounterMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CounterPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CounterTimelineDays")
                        .HasColumnType("int");

                    b.Property<string>("CoverLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpectedOutputs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpertProfileId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("PreliminaryMilestonePlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProposedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProposedTimelineDays")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("WorkingApproach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProposalId");

                    b.HasIndex("ExpertProfileId");

                    b.HasIndex("JobId", "ExpertProfileId")
                        .IsUnique();

                    b.HasIndex("JobId", "Status");

                    b.ToTable("Proposals", (string)null);
                });

            modelBuilder.Entity("AITasker.Domain.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RevieweeId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reviews_Reviewer_Reviewee", "[ReviewerId] <> [RevieweeId]");
                        });
                });

            modelBuilder.Entity("AITasker.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SkillId");

                    b.HasIndex("SkillName")
                        .IsUnique();

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            Category = "AI Application",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thiết kế và triển khai chatbot cho website, fanpage hoặc hệ thống nội bộ.",
                            IsActive = true,
                            SkillName = "Chatbot"
                        },
                        new
                        {
                            SkillId = 2,
                            Category = "AI Core",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Xử lý ngôn ngữ tự nhiên, phân loại văn bản, trích xuất ý định.",
                            IsActive = true,
                            SkillName = "NLP"
                        },
                        new
                        {
                            SkillId = 3,
                            Category = "LLM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tích hợp API LLM như OpenAI vào sản phẩm.",
                            IsActive = true,
                            SkillName = "OpenAI API"
                        },
                        new
                        {
                            SkillId = 4,
                            Category = "Programming",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lập trình Python cho AI, automation và data pipeline.",
                            IsActive = true,
                            SkillName = "Python"
                        },
                        new
                        {
                            SkillId = 5,
                            Category = "AI Core",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Xử lý ảnh, nhận diện đối tượng, phân loại ảnh.",
                            IsActive = true,
                            SkillName = "Computer Vision"
                        },
                        new
                        {
                            SkillId = 6,
                            Category = "Document AI",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trích xuất chữ từ ảnh, PDF, hóa đơn và tài liệu scan.",
                            IsActive = true,
                            SkillName = "OCR"
                        },
                        new
                        {
                            SkillId = 7,
                            Category = "Data",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phân tích dữ liệu, dashboard, metrics và insight.",
                            IsActive = true,
                            SkillName = "Data Analytics"
                        },
                        new
                        {
                            SkillId = 8,
                            Category = "Automation",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tự động hóa quy trình nghiệp vụ và báo cáo.",
                            IsActive = true,
                            SkillName = "Automation"
                        },
                        new
                        {
                            SkillId = 9,
                            Category = "LLM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thiết kế prompt, workflow LLM và đánh giá output.",
                            IsActive = true,
                            SkillName = "Prompt Engineering"
                        },
                        new
                        {
                            SkillId = 10,
                            Category = "LLM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Retrieval-Augmented Generation cho tài liệu nội bộ.",
                            IsActive = true,
                            SkillName = "RAG"
                        },
                        new
                        {
                            SkillId = 11,
                            Category = "Data",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thiết kế truy vấn, xử lý dữ liệu và báo cáo từ database.",
                            IsActive = true,
                            SkillName = "SQL"
                        },
                        new
                        {
                            SkillId = 12,
                            Category = "Data",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tạo dashboard và báo cáo trực quan.",
                            IsActive = true,
                            SkillName = "Power BI"
                        },
                        new
                        {
                            SkillId = 13,
                            Category = "Backend",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Xây dựng RESTful API bằng ASP.NET Core.",
                            IsActive = true,
                            SkillName = "ASP.NET Core"
                        },
                        new
                        {
                            SkillId = 14,
                            Category = "Backend",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Xây dựng realtime chat và notification.",
                            IsActive = true,
                            SkillName = "SignalR"
                        });
                });

            modelBuilder.Entity("AITasker.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("[GoogleId] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AITasker.Domain.Entities.BusinessProfile", b =>
                {
                    b.HasOne("AITasker.Domain.Entities.ClientProfile", "ClientProfile")
                        .WithOne("BusinessProfile")
                        .HasForeignKey("AITasker.Domain.Entities.BusinessProfile", "ClientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientProfile");
                });

            modelBuilder.Entity("AITasker.Domain.Entities.ClientProfile", b =>
                {
                    b.HasOne("AITasker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AITasker.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("AITasker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AITasker.Domain.Entities.ExpertCertificate", b =>
                {
                    b.HasOne("AITasker.Domain.Entities.ExpertProfile", "ExpertProfile")
                        .WithMany("Certificates")
                        .HasForeignKey("ExpertProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpertProfile");
                });

            modelBuilder.Entity("AITasker.Domain.Entities.ExpertProfile", b =>
                {
                    b.HasOne("AITasker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AITasker.Domain.Entities.ExpertSkill", b =>
                {
                    b.HasOne("AITasker.Domain.Entities.ExpertProfile", "ExpertProfile")
                        .WithMany()
                        .HasForeignKey("ExpertProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AITasker.Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpertProfile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AITasker.Domain.Entities.JobPosting", b =>
                {
                    b.HasOne("AITasker.Domain.Entities.ClientProfile", "ClientProfile")
                        .WithMany()
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientProfile");
                });

            modelBuilder.Entity("AITasker.Domain.Entities.JobSkill", b =>
                {
                    b.HasOne("AITasker.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AITasker.Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobPosting");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AITasker.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("AITasker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AITasker.Domain.Entities.Project", b =>
                {
                    b.HasOne("AITasker.Domain.Entities.ClientProfile", "ClientProfile")
                        .WithMany()
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AITasker.Domain.Entities.ExpertProfile", "ExpertProfile")
                        .WithMany()
                        .HasForeignKey("ExpertProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AITasker.Domain.Entities.Proposal", null)
                        .WithMany()
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClientProfile");

                    b.Navigation("ExpertProfile");
                });

            modelBuilder.Entity("AITasker.Domain.Entities.Proposal", b =>
                {
                    b.HasOne("AITasker.Domain.Entities.ExpertProfile", "ExpertProfile")
                        .WithMany()
                        .HasForeignKey("ExpertProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AITasker.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpertProfile");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("AITasker.Domain.Entities.Review", b =>
                {
                    b.HasOne("AITasker.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AITasker.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AITasker.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AITasker.Domain.Entities.ClientProfile", b =>
                {
                    b.Navigation("BusinessProfile");
                });

            modelBuilder.Entity("AITasker.Domain.Entities.ExpertProfile", b =>
                {
                    b.Navigation("Certificates");
                });

            modelBuilder.Entity("AITasker.Domain.Entities.JobPosting", b =>
                {
                    b.Navigation("JobSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
