namespace AITasker.Application.DTOs.Requests
{
    public class OpenDisputeRequest
    {
        public int ProjectId { get; set; }

        public int? MilestoneId { get; set; }

        public int? RespondentUserId { get; set; }

        public decimal DisputedAmount { get; set; }

        public string Reason { get; set; } = string.Empty;

        public string? EvidenceText { get; set; }

        // External file URL, for example Google Drive, PDF, ZIP, demo URL.
        public string? EvidenceFileUrl { get; set; }

        // External direct image URL. User does not need this when uploading image files.
        public string? EvidenceImageUrl { get; set; }

        // Internal uploaded image URLs generated by backend after multipart Images upload.
        public List<string> EvidenceImageUrls { get; set; } = new();
    }
}
